/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int PUT = 6;
  /** RegularExpression Id. */
  int PICK = 7;
  /** RegularExpression Id. */
  int POP = 8;
  /** RegularExpression Id. */
  int GO = 9;
  /** RegularExpression Id. */
  int SKP = 10;
  /** RegularExpression Id. */
  int DEFVAR = 11;
  /** RegularExpression Id. */
  int DEFUN = 12;
  /** RegularExpression Id. */
  int TURN = 13;
  /** RegularExpression Id. */
  int FACE = 14;
  /** RegularExpression Id. */
  int MOVEDIR = 15;
  /** RegularExpression Id. */
  int RUNDIRS = 16;
  /** RegularExpression Id. */
  int MOVEFACE = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int FRONT = 19;
  /** RegularExpression Id. */
  int RIGHT = 20;
  /** RegularExpression Id. */
  int LEFT = 21;
  /** RegularExpression Id. */
  int BACK = 22;
  /** RegularExpression Id. */
  int AROUND = 23;
  /** RegularExpression Id. */
  int NORTH = 24;
  /** RegularExpression Id. */
  int SOUTH = 25;
  /** RegularExpression Id. */
  int WEST = 26;
  /** RegularExpression Id. */
  int EAST = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int REPEAT = 29;
  /** RegularExpression Id. */
  int LOOP = 30;
  /** RegularExpression Id. */
  int FACING = 31;
  /** RegularExpression Id. */
  int BLOCKED = 32;
  /** RegularExpression Id. */
  int CANPICK = 33;
  /** RegularExpression Id. */
  int CANPUT = 34;
  /** RegularExpression Id. */
  int CANMOVE = 35;
  /** RegularExpression Id. */
  int ZERO = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int DP = 38;
  /** RegularExpression Id. */
  int LB = 39;
  /** RegularExpression Id. */
  int RB = 40;
  /** RegularExpression Id. */
  int Q = 41;
  /** RegularExpression Id. */
  int BALLOONS = 42;
  /** RegularExpression Id. */
  int CHIPS = 43;
  /** RegularExpression Id. */
  int CHAR = 44;
  /** RegularExpression Id. */
  int CONSTANT = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Move\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"Skip\"",
    "\"Defvar\"",
    "\"Defun\"",
    "\"Turn\"",
    "\"Face\"",
    "\"Move-dir\"",
    "\"run-dirs\"",
    "\"Move-face\"",
    "\"Null\"",
    "\"Front\"",
    "\"Right\"",
    "\"Left\"",
    "\"Back\"",
    "\"Around\"",
    "\"North\"",
    "\"South\"",
    "\"West\"",
    "\"East\"",
    "\"If\"",
    "\"Repeat\"",
    "\"Loop\"",
    "\"Facing\"",
    "\"Blocked\"",
    "\"Can-pick\"",
    "\"Can-put\"",
    "\"Can-move\"",
    "\"IsZero\"",
    "\"Not\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<CHAR>",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
    "\",\"",
  };

}
